@echo off
echo Closing running instances of game...
taskkill /f /im pico8.exe /fi "WINDOWTITLE eq BLOBUN_MINI.MIN.P8 (PICO-8)"
call do_compression.bat
echo Minifying cart...
..\shrinko\shrinko8.exe -f p8 -F p8 -M blobun_mini.p8 blobun_mini.min.p8
echo Minification done. Starting game...
start /wait pico8.exe -run blobun_mini.min.p8
echo Game closed