@echo off
echo Closing running instances of pico8...
taskkill /f /im pico8.exe /fi "WINDOWTITLE eq Blobun Mini"
echo Performing level conversion...
php level_convert.php
echo Performing compression routine...
start /wait pico8.exe -x compress_assets.p8
echo Starting the game...
start /wait pico8.exe -run blobun_mini.p8
echo Game closed