@echo off
echo Closing running instances of pico8...
taskkill /F /IM pico8.exe
echo Performing level conversion...
php level_convert.php
echo Performing compression routine...
start /wait pico8.exe -x compress_assets.p8
echo Starting the game...
start /wait pico8.exe -run blobun_mini.p8
echo Game closed