function menu_create(_x,_y,_w,_items)add(g_menu,{m_x=_x,m_y=_y,m_w=_w,m_h=count(_items)*10+6,m_items=_items,m_highlight=1,m_anim_incr=.25,m_anim_factor=0,m_step=function(self,_index)local _m_count=count(g_menu)local _is_top_pane,_pause_press,_i_count=_index==_m_count,btn(6),count(self.m_items)if(_pause_press)poke(24368,1)
if self.m_anim_factor==1then if(btnp(2))self.m_highlight-=1g_play_sfx=g_sfx_lut.m_sel
if(btnp(3))self.m_highlight+=1g_play_sfx=g_sfx_lut.m_sel
if(self.m_highlight<1)self.m_highlight=_i_count
if(self.m_highlight>_i_count)self.m_highlight=1
if(btnp(5)or btnp(4)or _pause_press)g_play_sfx=g_sfx_lut.m_confirm self.m_items[self.m_highlight]:i_onclick()
end local _do_anim=true if(_is_top_pane and _m_count>1and g_menu[_m_count-1].m_anim_factor>0)_do_anim=false
if(_do_anim)self.m_anim_factor=mid(0,self.m_anim_factor+(_is_top_pane and self.m_anim_incr or-.25),1)
if(self.m_anim_factor==0and self.m_anim_incr<0)deli(g_menu)
end,m_draw=function(self,_index)palt()local _m_count=count(g_menu)local _is_top_pane=_index==_m_count if(_is_top_pane and _m_count>1and g_menu[_m_count-1].m_anim_factor>0)return false
local _count,_sprchk,_b_h=count(self.m_items),count(g_list_obj)>0and 147or 241,lerp(5,self.m_h,self.m_anim_factor)local _x1,_y1,_is_hilite=self.m_x,self.m_y-(_b_h>>1)local _x2,_y2,_sx1,_sy1,_sx2,_sy2=_x1+self.m_w,_y1+_b_h rectfill(_x1,_y1,_x2,_y2,1)rect(_x1+1,_y1+1,_x2-1,_y2-1,13)local _base_x,_base_y=_x1+8,_y1+6for _ind,_item in pairs(self.m_items)do if _base_y<_y2-9then _sx1,_sy1,_sx2,_sy2=_x1+3,_base_y-3,_x2-3,_base_y+7_is_hilite=_ind==self.m_highlight if(_is_hilite)menu_draw_select(_sx1,_sy1,_sx2,_sy2)
pal(7,_is_hilite and 7or 13)?_item.i_label,_base_x,_base_y,7
if(_item.i_setting~=nil)spr(_sprchk-(setting_get(_item.i_setting)and 0or 1),_x2-11,_base_y-2)
end _base_y+=10end pal()end})end function menus_remove()for _pane in all(g_menu)do _pane.m_anim_incr=-.25end end function menu_goback()g_play_sfx=g_sfx_lut.m_back g_menu[count(g_menu)].m_anim_incr=-.25end function menu_item_base(_str,_func)return{i_label=_str,i_onclick=_func,i_setting=nil}end function menu_item_setting(_str,_setting)local _item=menu_item_base(_str,function(self)setting_set(self.i_setting,setting_get(self.i_setting)==false)if(self.i_setting==5)music(setting_get(5)and 0or-1,0,7)
end)_item.i_setting=_setting return _item end function menu_create_puzz()g_btn4_press,g_btn4_held,g_play_sfx=false,false,g_sfx_lut.m_confirm local _dest if(not g_final_world_clr and achv_beat_last_world())_dest=1
if(not g_game_clear and achv_beat_game_stages())_dest=2
if(not g_game_fast_clear and achv_beat_game_times(false))_dest=3
if(not g_game_dev_clear and achv_beat_game_times(true))_dest=4
if(_dest~=nil)set_game_mode(5,_dest)return
local _mi_np,_mi_rp,_mi_ss,_t=menu_item_base((g_stage_win and"next"or"skip").." puzzle",function()set_game_mode(2,g_p_i_world,g_p_i_stage+1)end),menu_item_base("restart puzzle",function()set_game_mode(2,g_p_i_world,g_p_i_stage,true)end),menu_item_base("stage select",function()set_game_mode(1)end)if(g_stage_win)_t={_mi_np,_mi_rp,_mi_ss}else _t={menu_item_base("back",menu_goback),_mi_rp,_mi_np,menu_item_base((g_arrow_index==2and"hide"or"show").." hints",function()g_arrow_index=g_arrow_index==2and 1or 2menus_remove()end),_mi_ss,menu_item_base("options",menu_create_options),menu_item_base("go to title",function()set_game_mode(0)end)}
menu_create(16,64,96,_t)end function menu_create_title()menu_create(24,96,80,{menu_item_base("start game",function()set_game_mode(1)end),menu_item_base("continue",function()local _ws=last_worldstage_get()set_game_mode(2,_ws.world,_ws.stage)end),menu_item_base("options",menu_create_options),menu_item_base("credits",function()set_game_mode(4)end),menu_item_base("back",menu_goback)})end function menu_create_options()menu_create(16,count(g_list_obj)>0and 64or 82,96,{menu_item_base("back",menu_goback),menu_item_setting("show timers",1),menu_item_setting("slime overlap",2),menu_item_setting("sprint by default",3),menu_item_setting("sound effects",4),menu_item_setting("music",5),menu_item_setting("lesbians allowed",6),menu_item_base("pico8 menu",menu_create_pico8)})end function menu_create_pico8()extcmd"pause"end function menu_draw_select(_x1,_y1,_x2,_y2)rectfill(_x1,_y1,_x2,_y2,2)fillp(g_fillp_diag[ceil(g_fillp_anim)])rect(_x1,_y1,_x2,_y2,154)fillp(0)end